---
blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Muhammad-Bello-Ibrahim/Connectest/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📧 Email Support
    url: mailto:mr.zplux009@gmail.com
    about: For private inquiries or security issues
